name: Experiment
on:
  push:
    branches:
      - main

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           fetch-depth: '0'
      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
      - name: Show new tag
        run: |
             echo " ${{ steps.tag_version.outputs.new_tag }}" 

  job2:
    name: Job 2
    needs: job1
    runs-on: ubuntu-latest 
    steps:
       - uses: actions/checkout@v2
       - name: Set up JDK 11 for x64
         uses: actions/setup-java@v2
         with:
          java-version: '11'
          distribution: adopt
          architecture: x64
       - name: Build with Maven
         run: mvn clean install --batch-mode

  job3:
    name: Job 3
    needs: job2
    runs-on: ubuntu-latest

    steps:
    - name: Will never run
      run: |
        echo "If you can read this, the experiment failed"
